"""Provider contracts and built-in registry for Pandora."""

from pandora_daemon.providers.contracts import (
    AccountOverview,
    ArchiveOption,
    ArchiveOptions,
    CommentVoteResult,
    FavoriteCategory,
    FavoritesPage,
    GalleryComment,
    GalleryDetail,
    GalleryProvider,
    GallerySearchQuery,
    GallerySummary,
    GalleryTorrent,
    RatingResult,
    TagCatalog,
    TagSuggestion,
    UserProfile,
    UserTag,
    ProviderContext,
)
from pandora_daemon.providers.errors import (
    ProviderAuthenticationError,
    ProviderContentBlockedError,
    ProviderError,
    ProviderGalleryNotFoundError,
    ProviderNetworkError,
    ProviderParseError,
    ProviderQuotaError,
    ProviderSessionError,
    ProviderUpstreamError,
)
from pandora_daemon.providers.registry import (
    ProviderFactory,
    ProviderRegistry,
    default_provider_registry,
)

__all__ = [
    "AccountOverview",
    "ArchiveOption",
    "ArchiveOptions",
    "CommentVoteResult",
    "FavoriteCategory",
    "FavoritesPage",
    "GalleryComment",
    "GalleryDetail",
    "GalleryProvider",
    "GallerySearchQuery",
    "GallerySummary",
    "GalleryTorrent",
    "RatingResult",
    "TagCatalog",
    "TagSuggestion",
    "UserProfile",
    "UserTag",
    "ProviderContext",
    "ProviderAuthenticationError",
    "ProviderContentBlockedError",
    "ProviderError",
    "ProviderGalleryNotFoundError",
    "ProviderNetworkError",
    "ProviderParseError",
    "ProviderQuotaError",
    "ProviderSessionError",
    "ProviderUpstreamError",
    "ProviderFactory",
    "ProviderRegistry",
    "default_provider_registry",
]
